#!/usr/bin/env python

# # Correlation analysis

# In[1]:


import pathlib
import sys
import warnings

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

sys.path.append("../../../")
from utils import data_utils

# ignore all warnings
warnings.filterwarnings("ignore")


# Helper functions

# In[2]:


def update_dmso_pathway_label(treatment: str, pathway: str) -> str:
    """
    Update the Pathway label for wells treated with DMSO.

    Parameters
    ----------
    treatment : str
        The treatment type, e.g., "DMSO-positive" or "DMSO-negative".
    pathway : str
        The current pathway label.

    Returns
    -------
    str
        Updated pathway label. If the treatment is "DMSO-positive" or "DMSO-negative",
        the pathway label is updated accordingly. Otherwise, the original pathway label is returned.
    """
    if treatment == "DMSO-positive":
        return "DMSO-positive"
    elif treatment == "DMSO-negative":
        return "DMSO-negative"
    else:
        return pathway


# Loading the data

# In[3]:


data_path = pathlib.Path("../UMAP-aggregated-fs-profiles/results/concat_data/batch_1_concat_agg_fs.csv")

# setting output path
output_path = pathlib.Path("results/")
output_path.mkdir(parents=True, exist_ok=True)


# In[4]:


# load the data
concat_profile_df = pd.read_csv(data_path)

# update the Pathway label for wells treated with DMSO
concat_profile_df["Metadata_Pathway"] = concat_profile_df.apply(
	lambda row: update_dmso_pathway_label(row["Metadata_treatment"], row["Metadata_Pathway"]), axis=1
)

# split the data into metadata and features
meta_cols, feat_cols = data_utils.split_meta_and_features(concat_profile_df)

concat_profile_df.head()


# ## Calculating correlation of each samples
#
# In this section fo the notebook, we build on our Pearson correlation analysis by visualizing the data with a seaborn clustermap. With each treatment linked to a specific pathway target, the clustergram not only groups samples based on morphological similarity but also allows us to observe whether treatments targeting the same pathway exhibit similar phenotypic profiles. This integrative approach provides insights into how specific pathway interventions drive morphological changes, thereby enhancing our biological interpretation of the treatment effects.

# In[5]:


# creating a dataframe with only the pathway and morphological features
pathway_df = concat_profile_df[["Metadata_treatment", "Metadata_Pathway"] + feat_cols]
pathway_df["Metadata_Pathway"].replace("NaN", "No Pathway", inplace=True)

# creating a dataframe with only morphological features
morph_df = pathway_df[feat_cols].copy()

# Calculate the pearson correlation between treated samples (well-level profiles)
sample_corr_matrix = morph_df.T.corr(method="pearson")

sample_corr_matrix.head()


# With the correlation matrix generated by calculating the correlation by each sample, then we create a clustergram where the axis represents the pathway of each treament, and the color gradient represents the correlation between samples.With the correlation matrix computed from each sample’s morphological profile, we generate a clustergram using seaborn. In this visualization, the axes are annotated with the pathway targets associated with each treatment, while the color gradient reflects the strength of the correlation between samples, enabling us to identify clusters of treatments with similar phenotypic responses.

# In[6]:


# plot the correlation matrix
plt.figure(figsize=(12, 12))

# create a color bar for the unique pathways
unique_pathways = pathway_df["Metadata_Pathway"].unique()
pathway_colors = sns.color_palette("tab20", len(unique_pathways))
pathway_color_dict = dict(zip(unique_pathways, pathway_colors))


# create a color map for the treatments
pathway_color_map = pathway_df["Metadata_Pathway"].map(pathway_color_dict)

# using seaborn, plot a clustermap
sample_corr_clustermap = sns.clustermap(
    sample_corr_matrix,
    row_colors=pathway_color_map,
    col_colors=pathway_color_map,
    cmap="coolwarm",
    figsize=(12, 12),
    xticklabels=1,
    yticklabels=1,
    cbar_pos=(0.90, 0.50, 0.02, 0.2)
)

# adding title to the clustermap figure
sample_corr_clustermap.fig.suptitle("Correaltion Clustermap of Treated Samples", fontsize=16, y=1.01)

# remove x and y ticks and labels
sample_corr_clustermap.ax_heatmap.set_xticklabels([])
sample_corr_clustermap.ax_heatmap.set_yticklabels([])
sample_corr_clustermap.ax_heatmap.set_xticks([])
sample_corr_clustermap.ax_heatmap.set_yticks([])

# adding the Pathway legend to the cluster map
handles = [mpatches.Patch(color=color, label=pathway) for pathway, color in pathway_color_dict.items()]
sample_corr_clustermap.fig.legend(handles=handles, title="Pathway", loc="upper right", bbox_to_anchor=(1.09, 0.49))

# now taking the colobar legend and adding a title
cbar = sample_corr_clustermap.ax_heatmap.collections[0].colorbar
cbar.ax.set_title("Correlation", fontsize=11, x=0.5, y=1.02)

# save the figure
output_file = output_path / "sample_corr_clustermap.png"
sample_corr_clustermap.savefig(output_file, dpi=500, bbox_inches="tight")

sample_corr_clustermap


# ## Correlation matrix sorted by treatment name

# In[7]:


# calculate the correlation
concat_profile_df = concat_profile_df.sort_values(by=["Metadata_treatment"])
sorted_morph_df = concat_profile_df[feat_cols].copy()
sorted_treatment_corr_matrix = sorted_morph_df.corr(method="pearson")


# In[8]:


# Set the figure size and resolution
plt.figure(figsize=(10, 7))

# Plot the heatmap of the correlation matrix of morphological features
corr_heatmap = sns.heatmap(sorted_treatment_corr_matrix, cmap="coolwarm")

# Remove the x and y axis tick labels for better visualization
corr_heatmap.set(xticklabels=[])
corr_heatmap.set(yticklabels=[])
corr_heatmap.set_xticks([])
corr_heatmap.set_yticks([])

# Set the title of the heatmap
corr_heatmap.set_title("Correlation heatmap of morphological features (sorted by treatment)")

# Set the title of the color bar (legend)
corr_heatmap.collections[0].colorbar.set_label("Correlation")

# save the correlation heatmap
plt.savefig(output_path / "correlation_morph_sorted_treatments.png", dpi=500)

# Display the heatmap
corr_heatmap


# ## Correlation cluster gram of morphological features

# In[9]:


morph_df = concat_profile_df[feat_cols].copy()
morph_labels = [colname.split("_")[0] for colname in feat_cols]
corr_morph_df = morph_df.corr(method="pearson")


# In[10]:


# setting figure size
plt.figure(figsize=(12, 12))

# creating a color bar for the unique morphological features stain
unique_morph_labels = list(set(morph_labels))
morph_colors = sns.color_palette("tab10", len(unique_morph_labels))
morph_color_dict = dict(zip(unique_morph_labels, morph_colors))

# create a color map for the morphological features
morph_color_map = pd.Series(morph_labels, index=feat_cols).map(morph_color_dict)

# generate seaborn clustermap with a larger figure size
clustermap = sns.clustermap(
    corr_morph_df.corr(method="pearson"),
    cmap="coolwarm",
    row_colors=morph_color_map,
    col_colors=morph_color_map,
    figsize=(12, 12),
    xticklabels=1,
    yticklabels=1,
)

# next remove the X and Y axis labels for better visualization and ticks
clustermap.ax_heatmap.set(xticklabels=[])
clustermap.ax_heatmap.set(yticklabels=[])
clustermap.ax_heatmap.set_xticks([])
clustermap.ax_heatmap.set_yticks([])

# Set the title of the clustermap
clustermap.fig.suptitle("Correlation cluster-heatmap of morphological features", x=0.37, y=1., fontsize=13)

# adding the Morphological features legend to the cluster map
handles = [mpatches.Patch(color=color, label=label) for label, color in morph_color_dict.items()]
clustermap.fig.legend(handles=handles, title="Compartment", loc="upper right", bbox_to_anchor=(.73, .97), fontsize=9)

# move color gradient to the left side
clustermap.ax_heatmap.collections[0].colorbar.set_label("Correlation")
clustermap.cax.set_position([0.65, 0.39, 0.02, 0.45])

# save the clustermap to a file
clustermap.savefig(output_path / "clustermap_morph_features.png", dpi=500)
clustermap
