general_configs:
  # General configurations for this project:
  # seed (int): Seed value for ensuring reproducibility in analyses that involve random
  # operations
  #
  # root_anchor (str): A relative path to a specific file or directory used as a reference
  # (anchor) to determine the project's root directory. Example: If the project root
  # contains a .git/ folder, this can be used to dynamically locate the root directory
  # regardless of the script's location.
  seed: 0
  root_anchor: .git/  # Default anchor pointing to the .git directory at the project root


download_configs:
  # Data download configurations:
  #
  # download_chunk_size (int): The size (in KB) of data chunks to download at a time for
  # optimized performance
  #
  # github_metadata_url (str): The URL of the dataset source. In this case, the file
  # being downloaded is a zip archive, as the source contains a directory.
  download_chunk_size: 128
  github_metadata_url: https://github.com/WayScience/targeted_fibrosis_drug_screen/archive/refs/heads/main.zip


copairs_ap_configs:
  # This section contains the configurations used for calculating AP
  # (Average Precision)
  #
  # pos_sameby (list[str]): Using metadata to identify profiles that belong to the same
  # group, that is not the control group (e.g if using some sort of sample id, profiles
  # that have the same sample ID are considered as positive pairs that have the same
  # positive ID)
  #
  # pos_diffby (list[str]): Metadata columns used to differentiate positive pairs. If
  # specified, positive # pairs must differ in these columns (e.g., batch identifiers).
  # Leave empty if no differentiation is required.
  #
  # neg_sameby (list[str]): Metadata columns used to define negative pairs. Negative
  # pairs are profiles that share the same values in these columns. Typically left
  # empty for mAP.
  #
  # neg_diffby (list[str]): Define negative pairs as profiles where one belongs to a group
  # of compound replicates and the other to DMSO controls, ensuring they differ in both
  # the compound identifier and reference index columns specified in neg_diffby.
  #
  # batch_size (int): The batch size for processing similarity computations Larger
  # values use more memory but process faster.
  #
  # distance (str): The distance metric used for similarity computations. Common options
  # include "cosine". Other options can be found here:
  # https://github.com/cytomining/copairs/blob/main/src/copairs/compute.py
  #
  pos_sameby: ["Metadata_treatment"]
  pos_diffby: []
  neg_sameby: []
  neg_diffby: ["Metadata_treatment", "Metadata_treatment"]
  batch_size: 20000
  distance: cosine
